# Generated by Django 4.2 on 2023-06-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('disco_info', models.CharField(max_length=15)),
                ('cpu_info', models.CharField(max_length=15)),
                ('memoria_info', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('intentos', models.PositiveIntegerField()),
                ('fecha_ultimo_intento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('hostname', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=254)),
                ('chat_id', models.CharField(max_length=70)),
                ('bot_token', models.CharField(max_length=70)),
                ('token_otp', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.servicio')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.usuario')),
            ],
        ),
    ]
